export const enum KEYS {
  C = 'C',
  X = 'X',
  Z = 'Z',
  Y = 'Y',
  A = 'A',
  G = 'G',
  L = 'L',
  F = 'F',
  D = 'D',
  B = 'B',
  P = 'P',
  O = 'O',
  R = 'R',
  T = 'T',
  MINUS = '-',
  EQUAL = '=',
  DIGIT_0 = '0',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  SPACE = ' ',
  TAB = 'TAB',
  BACKSPACE = 'BACKSPACE',
  ESC = 'ESCAPE',
  PAGEUP = 'PAGEUP',
  PAGEDOWN = 'PAGEDOWN',
  F5 = 'F5',
}

interface HotkeyItem {
  type: string;
  children: {
    label: string;
    value?: string;
  }[];
}

export const HOTKEY_DOC: HotkeyItem[] = [
  {
    type: 'Umum',
    children: [
      { label: 'Potong', value: 'Ctrl + X' },
      { label: 'Salin', value: 'Ctrl + C' },
      { label: 'Tempel', value: 'Ctrl + V' },
      { label: 'Tempel sebagai Teks Biasa', value: 'Ctrl + Shift + V' },
      { label: 'Salin & Tempel Cepat', value: 'Ctrl + D' },
      { label: 'Pilih Semua', value: 'Ctrl + A' },
      { label: 'Urungkan', value: 'Ctrl + Z' },
      { label: 'Ulangi', value: 'Ctrl + Y' },
      { label: 'Hapus', value: 'Delete / Backspace' },
      { label: 'Pilih Banyak', value: 'Tahan Ctrl atau Shift' },
      { label: 'Buka Cari & Ganti', value: 'Ctrl + F' },
      { label: 'Cetak', value: 'Ctrl + P' },
      { label: 'Tutup Dialog', value: 'ESC' },
    ],
  },
  {
    type: 'Presentasi Slide',
    children: [
      { label: 'Mulai Presentasi dari Awal', value: 'F5' },
      { label: 'Mulai Presentasi dari Slide Saat Ini', value: 'Shift + F5' },
      { label: 'Halaman Sebelumnya', value: '↑ / ← / PgUp' },
      { label: 'Halaman Berikutnya', value: '↓ / → / PgDown' },
      { label: 'Halaman Berikutnya', value: 'Enter / Space' },
      { label: 'Keluar Presentasi', value: 'ESC' },
    ],
  },
  {
    type: 'Edit Slide',
    children: [
      { label: 'Buat Slide Baru', value: 'Enter' },
      { label: 'Geser Kanvas', value: 'Space + Seret Mouse' },
      { label: 'Zoom Kanvas', value: 'Ctrl + Scroll Mouse' },
      { label: 'Perbesar Kanvas', value: 'Ctrl + =' },
      { label: 'Perkecil Kanvas', value: 'Ctrl + -' },
      { label: 'Sesuaikan Kanvas ke Layar', value: 'Ctrl + 0' },
      { label: 'Halaman Sebelumnya (Tanpa Elemen Terpilih)', value: '↑' },
      { label: 'Halaman Berikutnya (Tanpa Elemen Terpilih)', value: '↓' },
      { label: 'Halaman Sebelumnya', value: 'Scroll Atas / PgUp' },
      { label: 'Halaman Berikutnya', value: 'Scroll Bawah / PgDown' },
      { label: 'Buat Teks Cepat', value: 'Klik Ganda Area Kosong / T' },
      { label: 'Buat Persegi Cepat', value: 'R' },
      { label: 'Buat Lingkaran Cepat', value: 'O' },
      { label: 'Buat Garis Cepat', value: 'L' },
      { label: 'Keluar Mode Gambar', value: 'Klik Kanan Mouse' },
    ],
  },
  {
    type: 'Operasi Elemen',
    children: [
      { label: 'Pindahkan', value: '↑ / ← / ↓ / →' },
      { label: 'Kunci', value: 'Ctrl + L' },
      { label: 'Gabungkan', value: 'Ctrl + G' },
      { label: 'Pisahkan Grup', value: 'Ctrl + Shift + G' },
      { label: 'Pindah ke Paling Depan', value: 'Alt + F' },
      { label: 'Pindah ke Paling Belakang', value: 'Alt + B' },
      { label: 'Kunci Rasio Aspek', value: 'Tahan Ctrl atau Shift' },
      { label: 'Buat Garis Horizontal / Vertikal', value: 'Tahan Ctrl atau Shift' },
      { label: 'Pindah Fokus Elemen', value: 'Tab' },
      { label: 'Konfirmasi Pemotongan Gambar', value: 'Enter' },
      { label: 'Selesaikan Gambar Bentuk Kustom', value: 'Enter' },
    ],
  },
  {
    type: 'Edit Tabel',
    children: [
      { label: 'Fokus ke Sel Berikutnya', value: 'Tab' },
      { label: 'Pindahkan Fokus Sel', value: '↑ / ← / ↓ / →' },
      { label: 'Sisipkan Baris di Atas', value: 'Ctrl + ↑' },
      { label: 'Sisipkan Baris di Bawah', value: 'Ctrl + ↓' },
      { label: 'Sisipkan Kolom di Kiri', value: 'Ctrl + ←' },
      { label: 'Sisipkan Kolom di Kanan', value: 'Ctrl + →' },
    ],
  },
  {
    type: 'Edit Data Grafik',
    children: [{ label: 'Fokus ke Baris Berikutnya', value: 'Enter' }],
  },
  {
    type: 'Edit Teks',
    children: [
      { label: 'Tebal', value: 'Ctrl + B' },
      { label: 'Miring', value: 'Ctrl + I' },
      { label: 'Garis Bawah', value: 'Ctrl + U' },
      { label: 'Kode Inline', value: 'Ctrl + E' },
      { label: 'Superskrip', value: 'Ctrl + ;' },
      { label: 'Subskrip', value: `Ctrl + '` },
      { label: 'Pilih Paragraf', value: `ESC` },
    ],
  },
  {
    type: 'Pintasan Lainnya',
    children: [
      { label: 'Tambah Gambar - Tempel gambar dari clipboard sistem' },
      { label: 'Tambah Gambar - Seret gambar lokal ke kanvas' },
      { label: 'Tambah Gambar - Tempel kode SVG di kanvas' },
      { label: 'Tambah Gambar - Tempel tautan gambar dari Pexels' },
      { label: 'Tambah Teks - Tempel teks dari clipboard sistem' },
      { label: 'Tambah Teks - Seret teks dari luar ke kanvas' },
      { label: 'Edit Teks - Mendukung sintaks markdown untuk membuat daftar dan kutipan' },
    ],
  },
];
